# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Donkey < Formula
  desc "🫏 A small utility for batch file rpecessing using AI"
  homepage "https://github.com/evg4b/donkey"
  version "0.0.3"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/evg4b/donkey/releases/download/v0.0.3/donkey_Darwin_x86_64.tar.gz"
      sha256 "2d4e46649ce834636b2753c3ee0b49fdeb95c81a498f300dd64a62094467f9b6"

      def install
        bin.install "donkey"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/evg4b/donkey/releases/download/v0.0.3/donkey_Darwin_arm64.tar.gz"
      sha256 "9fdd071642b99532a444eef0dfba10d211c6e68066df771fbade36451b73ca64"

      def install
        bin.install "donkey"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/evg4b/donkey/releases/download/v0.0.3/donkey_Linux_x86_64.tar.gz"
        sha256 "24fe8ace217618abd55064f17e87a28dbacceddfb37b58bfd0955b41969f6d18"

        def install
          bin.install "donkey"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/evg4b/donkey/releases/download/v0.0.3/donkey_Linux_arm64.tar.gz"
        sha256 "6bc04ca6090c696c83c028a8ad2d02b3a63745b8028413c6529718a4fa47254f"

        def install
          bin.install "donkey"
        end
      end
    end
  end

  test do
    system "#{bin}/donkey", "--version"
  end
end
