# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Donkey < Formula
  desc "🫏 A small utility for batch file rpecessing using AI"
  homepage "https://github.com/evg4b/donkey"
  version "0.0.1"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/evg4b/donkey/releases/download/v0.0.1/donkey_Darwin_x86_64.tar.gz"
      sha256 "8f546e45ec691fc3b7a625162659f7b747dbbb534c848efdce95cecb62f6c2a2"

      def install
        bin.install "donkey"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/evg4b/donkey/releases/download/v0.0.1/donkey_Darwin_arm64.tar.gz"
      sha256 "f267a8edcc16a4b8a74d7106b66e1a2335d6be0a018cdd8e39fa7308aa107410"

      def install
        bin.install "donkey"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/evg4b/donkey/releases/download/v0.0.1/donkey_Linux_x86_64.tar.gz"
        sha256 "cbcbebdfe748d8a19a4c890e92e44e4e63babf8c3c044880a8a9054d55a2cc32"

        def install
          bin.install "donkey"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/evg4b/donkey/releases/download/v0.0.1/donkey_Linux_arm64.tar.gz"
        sha256 "4b09dfecd650148e60b6b53f1e1dc70187efbb6faf8d3520ca404e2a18a99993"

        def install
          bin.install "donkey"
        end
      end
    end
  end

  test do
    system "#{bin}/donkey", "--version"
  end
end
