# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Donkey < Formula
  desc "🫏 A small utility for batch file rpecessing using AI"
  homepage "https://github.com/evg4b/donkey"
  version "0.0.2"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/evg4b/donkey/releases/download/v0.0.2/donkey_Darwin_x86_64.tar.gz"
      sha256 "a6a2ddaf8fc05f5d02eea4ef5d25c2eeec9dfcf65ea6b02a8180f544340a2c25"

      def install
        bin.install "donkey"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/evg4b/donkey/releases/download/v0.0.2/donkey_Darwin_arm64.tar.gz"
      sha256 "c6d9c277d95979eaa41ac6f7eae4462ac705c4cf1b8fac5e6472797180f28a53"

      def install
        bin.install "donkey"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/evg4b/donkey/releases/download/v0.0.2/donkey_Linux_x86_64.tar.gz"
        sha256 "7d58b8f39bb5bcec63e8bfb635fdbf11542a8d4eb8843778da89aac7371075a1"

        def install
          bin.install "donkey"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/evg4b/donkey/releases/download/v0.0.2/donkey_Linux_arm64.tar.gz"
        sha256 "6d5ed181986d848cb6796e04000112ab524d3105caddd4d6b003800e1c446aef"

        def install
          bin.install "donkey"
        end
      end
    end
  end

  test do
    system "#{bin}/donkey", "--version"
  end
end
