# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uncors < Formula
  desc "A simple dev HTTP/HTTPS proxy for replacing CORS headers."
  homepage "https://github.com/evg4b/uncors"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/evg4b/uncors/releases/download/v0.0.5/uncors_0.0.5_darwin_arm64.tar.gz"
      sha256 "d76cb72dde9febbaf42fb7c5cd6d10ade6baeaf0bb7b32c1c461d4b428e6017d"

      def install
        bin.install "uncors"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/evg4b/uncors/releases/download/v0.0.5/uncors_0.0.5_darwin_amd64.tar.gz"
      sha256 "b33cd09eb176c8af2be65f78fa828a5f64c8c39f19697d09368460509d96c595"

      def install
        bin.install "uncors"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/evg4b/uncors/releases/download/v0.0.5/uncors_0.0.5_linux_amd64.tar.gz"
      sha256 "423ee335a8fa1808f851935af01b50217f09864e32de025e8481abf6ef1285c2"

      def install
        bin.install "uncors"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/evg4b/uncors/releases/download/v0.0.5/uncors_0.0.5_linux_armv6.tar.gz"
      sha256 "8a5634cc042fb09ff36d0f61b223793f1ebf9921c2af1232839786697b651d98"

      def install
        bin.install "uncors"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/evg4b/uncors/releases/download/v0.0.5/uncors_0.0.5_linux_arm64.tar.gz"
      sha256 "a5e58cc5fd20e39a8cc4a415dba3262a21ebb2cd03dd257fe324c7393a63de4d"

      def install
        bin.install "uncors"
      end
    end
  end

  test do
    system "#{bin}/uncors", "--help"
  end
end
