# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uncors < Formula
  desc "A simple dev HTTP/HTTPS reverse proxy for replacing CORS headers."
  homepage "https://github.com/evg4b/uncors"
  version "0.0.8-beta"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/evg4b/uncors/releases/download/v0.0.8-beta/uncors_0.0.8-beta_MacOS_x86_64.tar.gz"
      sha256 "acc25862bd407d74765b6f2acbe78af1845e71d38af1134ac2ee32bb541d740c"

      def install
        bin.install "uncors"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/evg4b/uncors/releases/download/v0.0.8-beta/uncors_0.0.8-beta_MacOS_arm64.tar.gz"
      sha256 "05dbfb31570ad7d9487c7d49eb62f1c06aa1377bad8ca1c3285e85cab7871ca8"

      def install
        bin.install "uncors"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/evg4b/uncors/releases/download/v0.0.8-beta/uncors_0.0.8-beta_Linux_armv6.tar.gz"
      sha256 "63fa10984a3fd540c80c114b832036452ccf3dabf9ed872a9030b309219d6d25"

      def install
        bin.install "uncors"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/evg4b/uncors/releases/download/v0.0.8-beta/uncors_0.0.8-beta_Linux_x86_64.tar.gz"
      sha256 "a9dd186024669d851c227ea85cd561ef6f96dc511a8ed2944199c98d47a3e521"

      def install
        bin.install "uncors"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/evg4b/uncors/releases/download/v0.0.8-beta/uncors_0.0.8-beta_Linux_arm64.tar.gz"
      sha256 "0bb4241abd86d304cfa4529d68f4f6cb1d7bf27d8a67af49f37c16f2d008f195"

      def install
        bin.install "uncors"
      end
    end
  end

  test do
    system "#{bin}/uncors", "--help"
  end
end
